# Generated by Django 5.0.4 on 2024-05-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('number_of_people', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
