# Generated by Django 5.0.4 on 2024-05-01 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_table_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number_of_people',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
